# Site settings
title: Sebastian Daza
header-img: img/demography2.jpg
email: sebastian.daza@gmail.com
copyright_name: Sebastian Daza
description: "Sebastian Daza Blog"
# baseurl: ""
url: "http://sdaza.com"
twitter_username: sebadaza
github_username:  sdaza
# facebook_username:  Sebastian Daza
email_username:  sebastian.daza

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# All Jekyll-Bootstrap specific configurations are namespaced into this hash

JB :
  version : 0.2.13

# Settings for analytics helper
  analytics :
    provider : google
    google :
        tracking_id : 'UA-34554402-2'
    getclicky :
      site_id :
    # mixpanel :
    #     token : '_MIXPANEL_TOKEN_'
