# Site settings
title: Sebastian Daza
header-img: img/demography2.jpg
email: sebastian.daza@gmail.com
copyright_name: Sebastian Daza
description: "Write your site description here. It will be used as your sites meta description as well!"
# baseurl: ""
url: "http://sdaza.com"
twitter_username: sebadaza
github_username:  sdaza
# facebook_username:  Sebastian Daza
email_username:  sebastian.daza

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
